---
name: lifecycle-demo
director_uuid: <%= `bosh status --uuid` %>

releases:
  - name: lifecycle-demo
    version: latest

networks:
  - name: default
    type: manual
    subnets:
      - range: 192.168.0.0/24
        cloud_properties: {net_id: <net-id>}
        reserved: [192.168.0.2-192.168.0.10]
        gateway: 192.168.0.1
        static: [192.168.0.13,192.168.0.14,192.168.0.15]

jobs:
  - name: demo-job
    templates:
      - {name: demo, release: lifecycle-demo}
      - {name: demo2, release: lifecycle-demo}
    networks:
      - name: default
    instances: 1
    resource_pool: small_pool

  - name: another-demo-job
    templates:
      - {name: demo, release: lifecycle-demo}
      - {name: demo2, release: lifecycle-demo}
    networks:
      - name: default
    instances: 1
    resource_pool: small_pool

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.medium

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 3000-600000
  update_watch_time: 5000-600000

resource_pools:
  - name: small_pool
    network: default
    cloud_properties:
      instance_type: m1.large
      security_groups: ["bosh"]
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: 3262.12
